@startuml structure
scale 3

[MultivariateDiscretizer] as md
[discretization] as disc
[util] as util
[structure] as stru

md --> disc
md --> util
md --> stru
stru --> util

@enduml
@startuml markov-blanket
scale 3

(A)
(E)
(H)
(I)

cloud Markov-takaró {
(B)
(C)
(D) #pink;line:blue;line.bold;text:blue
(F)
(G)
}

A --> B
B --> D
C --> D
D --> G
E --> F
F --> G
F --> I
G --> H


@enduml