@startuml structure
scale 3

folder test as test_folder {
    [test] as test
    [unit_test] as ut
}

package bediscretizer {
[MultivariateDiscretizer] as md
[discretization] as disc
[util] as util
[structure] as stru
}

md --> disc
md --> util
md --> stru
stru --> util

test --> md
ut --> util

@enduml
@startuml markov-blanket
scale 3

(A)
(E)
(H)
(I)

cloud Markov-takaró {
(B)
(C)
(D) #pink;line:blue;line.bold;text:blue
(F)
(G)
}

A --> B
B --> D
C --> D
D --> G
E --> F
F --> G
F --> I
G --> H


@enduml
@startuml pelda-bayes
scale 3

(CPU hűtés\nhiba) as A
(Zaj) as B
(Túlmelegedés) as C

label "P(+) = 0.01\nP(-) = 0.99"

A --> B : "P(+ | +) = 0.70\nP(- | +) = 0.30\nP(+ | -) = 0.35\nP(- | -) = 0.65"
A --> C : "P(+ | +) = 0.80\nP(- | +) = 0.20\nP(+ | -) = 0.10\nP(- | -) = 0.90"

@enduml